### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/quick-reaction-game#2]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md
- [x] diagram
- [x] schematic

**Comment by lauraclay** [comment]
Images need to be moved into the images folder and links updated.

**Comment by MissPhilbin** [comment]
Add images to correct folder. New diagram and schematic added ready for Sam @bennuttall

**Comment by bennuttall** [comment]
Added cover image

**Comment by bennuttall** [comment]
No new components required, but the resistor value needs adding.

**Comment by MissPhilbin** [comment]
330 ohms - where do I add this info?

**Comment by bennuttall** [comment]
[hardware.yml](https://github.com/raspberrypilearning/quick-reaction-game/blob/master/hardware.yml)

The "name" field contains the text that accompanies the image.
